name: Theme Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
